apiVersion: apps/v1
kind: Deployment
metadata: { name: collector }
spec:
  replicas: 1
  selector: { matchLabels: { app: collector } }
  template:
    metadata: { labels: { app: collector } }
    spec:
      containers:
      - name: collector
        image: collector-service:v1
        ports: [{containerPort: 8001}]
---
apiVersion: v1
kind: Service
metadata: { name: collector-service }
spec:
  type: NodePort
  selector: { app: collector }
  ports:
  - port: 8001
    targetPort: 8001
    nodePort: 31111