apiVersion: apps/v1
kind: Deployment
metadata: { name: producer }
spec:
  replicas: 1
  selector: { matchLabels: { app: producer } }
  template:
    metadata: { labels: { app: producer } }
    spec:
      containers:
      - name: producer
        image: producer-service:v1
        ports: [{containerPort: 8000}]
---
apiVersion: v1
kind: Service
metadata: { name: producer-service }
spec:
  type: NodePort
  selector: { app: producer }
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30222